version: "3.8"

services:
  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./BE/.env
    depends_on:
      - sql_server
      - mongodb

  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

  sql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Password123"
    ports:
      - "1433:1433"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
