export const PROVINCE_TO_BRANCH_CODE_MAP: Record<string, string> = {
    // === Miền Bắc (HN) ===
    "Thành phố Hà Nội": "HN",
    "Thành phố Hải Phòng": "HN",
    "Tỉnh Hải Dương": "HN",
    "Tỉnh Hưng Yên": "HN",
    "Tỉnh Thái Bình": "HN",
    "Tỉnh Nam Định": "HN",
    "Tỉnh Hà Nam": "HN",
    "Tỉnh Ninh Bình": "HN",
    "Tỉnh Quảng Ninh": "HN",
    "Tỉnh Bắc Giang": "HN",
    "Tỉnh Bắc Ninh": "HN",
    "Tỉnh Vĩnh Phúc": "HN",
    "Tỉnh Phú Thọ": "HN",
    "Tỉnh Tuyên Quang": "HN",
    "Tỉnh Lào Cai": "HN",
    "Tỉnh Yên Bái": "HN",
    "Tỉnh Hà Giang": "HN",
    "Tỉnh Cao Bằng": "HN",
    "Tỉnh Bắc Kạn": "HN",
    "Tỉnh Thái Nguyên": "HN",
    "Tỉnh Lai Châu": "HN",
    "Tỉnh Sơn La": "HN",
    "Tỉnh Điện Biên": "HN",
    "Tỉnh Hòa Bình": "HN",

    // === Miền Trung & Tây Nguyên (DN) ===
    "Thành phố Đà Nẵng": "DN",
    "Tỉnh Thanh Hóa": "DN",
    "Tỉnh Nghệ An": "DN",
    "Tỉnh Hà Tĩnh": "DN",
    "Tỉnh Quảng Bình": "DN",
    "Tỉnh Quảng Trị": "DN",
    "Tỉnh Thừa Thiên Huế": "DN",
    "Tỉnh Quảng Nam": "DN",
    "Tỉnh Quảng Ngãi": "DN",
    "Tỉnh Bình Định": "DN",
    "Tỉnh Phú Yên": "DN",
    "Tỉnh Khánh Hòa": "DN",
    "Tỉnh Ninh Thuận": "DN",
    "Tỉnh Bình Thuận": "DN",
    "Tỉnh Kon Tum": "DN",
    "Tỉnh Gia Lai": "DN",
    "Tỉnh Đắk Lắk": "DN",
    "Tỉnh Đắk Nông": "DN",
    "Tỉnh Lâm Đồng": "DN",

    // === Miền Nam (HCM) ===
    "Thành phố Hồ Chí Minh": "HCM",
    "Tỉnh Bà Rịa - Vũng Tàu": "HCM",
    "Tỉnh Bình Dương": "HCM",
    "Tỉnh Bình Phước": "HCM",
    "Tỉnh Đồng Nai": "HCM",
    "Tỉnh Tây Ninh": "HCM",
    "Tỉnh An Giang": "HCM",
    "Tỉnh Bạc Liêu": "HCM",
    "Tỉnh Bến Tre": "HCM",
    "Tỉnh Cà Mau": "HCM",
    "Thành phố Cần Thơ": "HCM",
    "Tỉnh Đồng Tháp": "HCM",
    "Tỉnh Hậu Giang": "HCM",
    "Tỉnh Kiên Giang": "HCM",
    "Tỉnh Long An": "HCM",
    "Tỉnh Sóc Trăng": "HCM",
    "Tỉnh Tiền Giang": "HCM",
    "Tỉnh Trà Vinh": "HCM",
    "Tỉnh Vĩnh Long": "HCM",

    // Admin (nếu cần)
    "Admin": "CT",
};
