export const PROVINCE_TO_BRANCH_CODE_MAP: { [key: string]: string } = {
    // === Miền Bắc (HN) ===
    'Hà Nội': 'HN',
    'Hải Phòng': 'HN',
    'Hải Dương': 'HN',
    'Hưng Yên': 'HN',
    'Thái Bình': 'HN',
    'Nam Định': 'HN',
    'Hà Nam': 'HN',
    'Ninh Bình': 'HN',
    'Quảng Ninh': 'HN',
    'Bắc Giang': 'HN',
    'Bắc Ninh': 'HN',
    'Vĩnh Phúc': 'HN',
    'Phú Thọ': 'HN',
    'Tuyên Quang': 'HN',
    'Lào Cai': 'HN',
    'Yên Bái': 'HN',
    'Hà Giang': 'HN',
    'Cao Bằng': 'HN',
    'Bắc Kạn': 'HN',
    'Thái Nguyên': 'HN',
    'Lai Châu': 'HN',
    'Sơn La': 'HN',
    'Điện Biên': 'HN',
    'Hoà Bình': 'HN',

    // === Miền Trung & Tây Nguyên (DN) ===
    'Đà Nẵng': 'DN',
    'Thanh Hoá': 'DN',
    'Nghệ An': 'DN',
    'Hà Tĩnh': 'DN',
    'Quảng Bình': 'DN',
    'Quảng Trị': 'DN',
    'Thừa Thiên Huế': 'DN',
    'Quảng Nam': 'DN',
    'Quảng Ngãi': 'DN',
    'Bình Định': 'DN',
    'Phú Yên': 'DN',
    'Khánh Hoà': 'DN',
    'Ninh Thuận': 'DN',
    'Bình Thuận': 'DN',
    'Kon Tum': 'DN',
    'Gia Lai': 'DN',
    'Đắk Lắk': 'DN', // Đắk Lắk -> DN
    'Đắk Nông': 'DN',
    'Lâm Đồng': 'DN',

    // === Miền Nam (HCM) ===
    'Hồ Chí Minh': 'HCM',
    'Bà Rịa - Vũng Tàu': 'HCM',
    'Bình Dương': 'HCM',
    'Bình Phước': 'HCM',
    'Đồng Nai': 'HCM',
    'Tây Ninh': 'HCM',
    'An Giang': 'HCM',
    'Bạc Liêu': 'HCM',
    'Bến Tre': 'HCM',
    'Cà Mau': 'HCM',
    'Cần Thơ': 'HCM',
    'Đồng Tháp': 'HCM',
    'Hậu Giang': 'HCM',
    'Kiên Giang': 'HCM',
    'Long An': 'HCM',
    'Sóc Trăng': 'HCM',
    'Tiền Giang': 'HCM',
    'Trà Vinh': 'HCM',
    'Vĩnh Long': 'HCM',

    "Admin": "CT"
};
